"""empty message

Revision ID: 0995a6583c99
Revises: 
Create Date: 2023-02-13 00:39:34.724429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0995a6583c99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('signature', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signature')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
